//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:27bcef36-0d79-4f20-9d57-1cf458f6e273
    public partial class QWERPanel
    {
        
        public const string NAME = "QWERPanel";
        
        [SerializeField()]
        public UnityEngine.UI.ScrollRect Scroll2;
        
        private QWERPanelData mPrivateData = null;
        
        public QWERPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        QWERPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new QWERPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Scroll2 = null;
            mData = null;
        }
    }
}
